NBADataAnalysis/urls.py
from django.contrib import admin
from django.urls import path, include
from NBADataAnalysis import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name='home'),
    path("about/", views.about, name='about'),
    path('update-league-leaders/', views.update_league_leaders, name='update_league_leaders'),
    path('show-career-awards-player1/<str:player1_name>/<str:player1_id>>', views.show_career_awards_player1, name='show_career_awards_player1'),
    path('show-career-awards-player2/<str:player2_name>/<str:player2_id>>', views.show_career_awards_player2, name='show_career_awards_player2'),
    path("stats/", include('nba_stats.urls')),
    # path("nba-news/", include('nba_news.urls')),
    # path("nba-today/", include('nba_today.urls')),
    # path("nba-teams/", include('nba_teams.urls')),
]

nba_stats/urls.py
from django.urls import path
from . import views

app_name = 'nba_stats'

urlpatterns = [

    path('player-comparison-search/', views.compare_players, name='compare_players'),
    path('update-player-awards/<str:player_name>/<str:player_id>', views.update_player_awards, name='update_player_awards'),
    path('update-player-bio/<str:player_name>/<str:player_id>', views.update_player_bio, name='update_player_bio'),
    path('graph-comparison/<str:player1_full_name>/<str:player1_id>/<str:player2_full_name>/<str:player2_id>/', views.show_graph, name='show_graph'),
    path('player-comparison-profiles/<str:player1_full_name>/<str:player1_id>/<str:player2_full_name>/<str:player2_id>/', views.compare_profiles, name='compare_profiles'),
    path('player-career-page/<str:player_full_name>/<str:player_id>/', views.player_details, name='player_details'),
    path('player-career-page/<str:player_full_name>/<str:player_id>/export/', views.export_career_stats, name='export_career_stats'),
    path('regular-season-totals/<str:player_full_name>/<str:player_id>/', views.regular_season, name='regular_season'),
    path('post-season-totals/<str:player_full_name>/<str:player_id>/', views.post_season, name='post_season'),
    path('regular-season-rankings/<str:player_full_name>/<str:player_id>/', views.regular_season_rankings,
         name='regular_season_rankings'),
    path('post-season-rankings/<str:player_full_name>/<str:player_id>/', views.post_season_rankings,
         name='post_season_rankings'),
    path('player-graph/<str:player_full_name>/<str:player_id>/<str:category>/', views.player_graph,
         name='player_graph'),
]

nba_stats/forms.py
from django import forms
from django.core import validators

STAT_OPTIONS = (
    ('--- View Stats By Year ---', '--- View Stats By Year  ---'),
    ('Reg. Season', 'Reg. Season'),
    ('Post Season', 'Post Season'),
    ('Reg. Season Rankings', 'Reg. Season Rankings'),
    ('Post Season Rankings', 'Post Season Rankings'),

)

STAT_OPTIONS2 = (
    ('--- Stats Totals By Year ---', '--- Stats Totals By Year  ---'),
    ('SeasonTotalsRegularSeason', 'Reg. Season'),
    ('SeasonTotalsPostSeason', 'Post Season'),
    ('SeasonRankingsRegularSeason', 'Reg. Season Rankings'),
    ('SeasonRankingsPostSeason', 'Post Season Rankings'),

)

# tuple where the first element is the value stored in the dictionary, and the second element is the user-readable
# option.
COMP_OPTIONS = (
    ('--- Compare Stats By Season ---', '--- Compare Stats By Season ---'),
    ('PPG', 'Points Per Game'),
    ('RPG', 'Rebs Per Game'),
    ('APG', 'Assists Per Game'),
    ('BLKPG', 'Blocks Per Game'),
    ('STLPG', 'Steals Per Game'),
    ('FG_PCT', 'Field Goal %'),
    ('FG3_PCT', '3 Point %'),
    ('FT_PCT', 'Free Thrown%'),
)

GRAPH_OPTIONS = (
    ('--- View Stat Graphs ---', '--- View Stat Graphs ---'),
    ('PPG', 'Points'),
    ('RPG', 'Rebounds'),
    ('APG', 'Assists'),
    ('BLKPG', 'Blocks'),
    ('STLPG', 'Steals'),
    ('FG_PCT', 'Field Goal %'),
    ('FG3_PCT', '3 Point %'),
    ('FT_PCT', 'Free Throw %'),
)


# form for searching a player
class PlayerSearchForm(forms.Form):
    player_name = forms.CharField(
        label='',
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Search a player',
                'class': 'form-control',
                'aria-label': 'Player Name'
            }
        ),
        error_messages={
            'required': 'Please enter a player name.',
            'max_length': 'Player name cannot exceed 100 characters.'
        }
    )


class TeamSearchForm(forms.Form):
    team_name = forms.CharField(
        label='',
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Enter a team',
                'class': 'form-control',
                'aria-label': 'Team Name'
            }
        ),
        error_messages={
            'required': 'Please enter the name or city of a NBA team.',
            'max_length': 'Team name cannot exceed 100 characters.'
        }
    )


# form for getting more stats
class StatsDropdownForm(forms.Form):
    option = forms.ChoiceField(choices=STAT_OPTIONS, label="Career Totals", required=True, error_messages={'required':'Please select an option'})

# form for stats comparison


class StatsCompForm(forms.Form):
    option = forms.ChoiceField(choices=COMP_OPTIONS, label="", required=True, error_messages={'required':'Please select an option'})

    # this method will allow me to get the selected option's readable value to use for the graph's title
    def get_graph_title(self, selected_option):
        for dict_value, reader_value in COMP_OPTIONS:
            if dict_value == selected_option:
                title = reader_value

        return title


# form for artist search
class PlayerCompareForm(forms.Form):
    player1 = forms.CharField(
        validators=[validators.MaxLengthValidator(50), validators.MinLengthValidator(1)],
        widget=forms.TextInput(attrs={'placeholder': 'Enter Player 1', 'style': 'width:300px'}))

    player2 = forms.CharField(
        validators=[validators.MaxLengthValidator(50), validators.MinLengthValidator(1)],
        widget=forms.TextInput(attrs={'placeholder': 'Enter Player 2', 'style': 'width:300px'}))


class PlayerGraphForm(forms.Form):
    career_category = forms.ChoiceField(label='Career Category', choices=STAT_OPTIONS, required=True, error_messages={'required':'Please select a category'})
    stat_option = forms.ChoiceField(choices=GRAPH_OPTIONS, label="Stat Category", required=True, error_messages={'required':'Please select a stat option'})

    # this method will allow me to get the selected option's readable value to use for the graph's title
    def get_graph_title(self, selected_option):
        for dict_value, reader_value in GRAPH_OPTIONS:
            if dict_value == selected_option:
                title = reader_value

        return title

nba_stats/views.py
from django.shortcuts import render, redirect
from .forms import PlayerSearchForm, StatsDropdownForm, PlayerCompareForm, StatsCompForm, PlayerGraphForm
from NBADataAnalysis.functions import *
from django.http import HttpResponse, HttpResponseRedirect
import pandas as pd
import logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')


def player_details(request, player_full_name, player_id):
    # session info will be from if the user clicks on either player1 or player2 on the home page
    logging.info("Fetching data from nba_api...")
    player_info = request.session.get("player_info", None)

    if player_info:

        # save data
        player_headshot = player_info[0]

        player_bio = player_info[1]

    elif player_info is None:
        # Search for the player data
        player_headshot, player_bio, player_id = fetch_player_data(player_full_name, player_id)

        player_headshot = [player_headshot.player_image_url, player_headshot.background_colour]

        del player_bio['_state']
    logging.info("Data successfully retrieved and stored in the database.")

    # Get player career stats
    career_stats = player_career_numbers(player_id)
    player_stats = career_stats['CareerTotalsRegularSeason']

    for season_data in player_stats:

        # points per game
        if season_data['GP'] > 0 and season_data['PTS'] is not None:
            season_data['PPG'] = round(season_data['PTS'] / season_data['GP'], 2)
        else:
            season_data['PPG'] = 0  # To avoid division by zero in case GP is 0

        # assists per game
        if season_data['GP'] > 0 and season_data['AST'] is not None:
            season_data['APG'] = round(season_data['AST'] / season_data['GP'], 1)
        else:
            season_data['APG'] = 0

        # blocks per game
        if season_data['GP'] > 0 and season_data['BLK'] is not None:
            season_data['BLKPG'] = round(season_data['BLK'] / season_data['GP'], 1)
        else:
            season_data['BLKPG'] = 0

        # rebounds per game
        if season_data['GP'] > 0 and season_data['REB'] is not None:
            season_data['RPG'] = round(season_data['REB'] / season_data['GP'], 1)
        else:
            season_data['RPG'] = 0

        # steals per game
        if season_data['GP'] > 0 and season_data['STL'] is not None:
            season_data['STLPG'] = round(season_data['STL'] / season_data['GP'], 1)
        else:
            season_data['STLPG'] = 0

        # Certain players (specifically from before 1980) don't have a 3pt %
        if season_data['FG3_PCT'] is None:
            season_data['FG3_PCT'] = 0

    # get player awards
    #player_awards = get_player_awards(player_full_name, player_id)

    # save information in session for quicker access
    player_page_info = [player_headshot, player_bio, career_stats]
    request.session['player_page_info'] = player_page_info

    # Initialize forms
    player_form = PlayerSearchForm()
    form = StatsDropdownForm()
    graph_form = PlayerGraphForm()

    if request.method == 'POST':
        form = StatsDropdownForm(request.POST)
        if form.is_valid():
            stats_option = form.cleaned_data['option']

            # regular season numbers
            if stats_option == 'Reg. Season':
                return redirect('nba_stats:regular_season', player_id=player_id, player_full_name=player_full_name)

            elif stats_option == 'Post Season':
                return redirect('nba_stats:post_season', player_id=player_id, player_full_name=player_full_name)

            elif stats_option == 'Reg. Season Rankings':
                return redirect('nba_stats:regular_season_rankings', player_id=player_id,
                                player_full_name=player_full_name)

            elif stats_option == 'Post Season Rankings':
                return redirect('nba_stats:post_season_rankings', player_id=player_id,
                                player_full_name=player_full_name)

            else:
                return redirect('home')

        graph_form = PlayerGraphForm(request.POST)
        if graph_form.is_valid():
            career_category = graph_form.cleaned_data['career_category']
            stat_option = graph_form.cleaned_data['stat_option']

            title = graph_form.get_graph_title(stat_option)
            graph = get_player_graph(player_id=player_id, player_name=player_full_name, career_stats=career_stats,
                                     stat_category=stat_option, career_category=career_category,
                                     title=title)
            player_page_info.append(graph)
            return redirect('nba_stats:player_graph', player_id=player_id, player_full_name=player_full_name,
                            category=stat_option)

    context = {'player_form': player_form,
               'player_headshot': player_headshot,
               'player_full_name': player_full_name,
               'player_stats': player_stats,
               'player_id': player_id,
               'form': form,
               'player_bio': player_bio,
               'graph_form': graph_form
               }

    return render(request, 'nba_stats/career_stats.html', context=context)


# regular season totals
def regular_season(request, player_full_name, player_id):
    # get session info containing player headshot, bio awards and career stats
    logging.info("Fetching data from nba_api...")
    player_page_info = request.session.get("player_page_info", None)

    if player_page_info:
        player_headshot = player_page_info[0]
        player_bio = player_page_info[1]

        # get regular season stats
        career_stats = player_page_info[2]
        player_stats = career_stats['SeasonTotalsRegularSeason']

    else:
        # Get player headshot
        player_headshot = get_player_image(player_id)

        # Get players yearly numbers
        player_stats = player_regular_season(player_id)

        # get player bio
        player_bio = get_player_bio(player_full_name)
    logging.info("Data successfully retrieved and stored in the database.")

    for season_data in player_stats:

        # points per game
        if season_data['GP'] > 0 and season_data['PTS'] is not None:
            season_data['PPG'] = round(season_data['PTS'] / season_data['GP'], 2)
        else:
            season_data['PPG'] = 0  # To avoid division by zero in case GP is 0

        # assists per game
        if season_data['GP'] > 0 and season_data['AST'] is not None:
            season_data['APG'] = round(season_data['AST'] / season_data['GP'], 1)
        else:
            season_data['APG'] = 0

        # blocks per game
        if season_data['GP'] > 0 and season_data['BLK'] is not None:
            season_data['BLKPG'] = round(season_data['BLK'] / season_data['GP'], 1)
        else:
            season_data['BLKPG'] = 0

        # rebounds per game
        if season_data['GP'] > 0 and season_data['REB'] is not None:
            season_data['RPG'] = round(season_data['REB'] / season_data['GP'], 1)
        else:
            season_data['RPG'] = 0

        # steals per game
        if season_data['GP'] > 0 and season_data['STL'] is not None:
            season_data['STLPG'] = round(season_data['STL'] / season_data['GP'], 1)
        else:
            season_data['STLPG'] = 0

        # Certain players (specifically from before 1980) don't have a 3pt %
        if season_data['FG3_PCT'] is None:
            season_data['FG3_PCT'] = 0

    # Initialize forms
    player_form = PlayerSearchForm()

    context = {'player_form': player_form,
               'player_headshot': player_headshot,
               'player_full_name': player_full_name,
               'player_stats': player_stats,
               'player_id': player_id,
               'player_bio': player_bio,
               #'player_awards': player_awards
               }

    return render(request, 'nba_stats/regular_season.html', context=context)


# post season totals
def post_season(request, player_full_name, player_id):
    # get session info containing player headshot, bio awards and career stats
    logging.info("Fetching data from nba_api...")
    player_page_info = request.session.get("player_page_info", None)

    if player_page_info:
        player_headshot = player_page_info[0]
        player_bio = player_page_info[1]

        # get regular season stats
        career_stats = player_page_info[2]
        player_stats = career_stats['SeasonTotalsPostSeason']

    else:
        # Get player headshot
        player_headshot = get_player_image(player_id, player_full_name)

        # Get players yearly numbers
        player_stats = player_post_season(player_id)

        # get player bio
        player_bio = get_player_bio(player_full_name)
    logging.info("Data successfully retrieved and stored in the database.")

    for season_data in player_stats:

        # points per game
        if season_data['GP'] > 0 and season_data['PTS'] is not None:
            season_data['PPG'] = round(season_data['PTS'] / season_data['GP'], 2)
        else:
            season_data['PPG'] = 0  # To avoid division by zero in case GP is 0

        # assists per game
        if season_data['GP'] > 0 and season_data['AST'] is not None:
            season_data['APG'] = round(season_data['AST'] / season_data['GP'], 1)
        else:
            season_data['APG'] = 0

        # blocks per game
        if season_data['GP'] > 0 and season_data['BLK'] is not None:
            season_data['BLKPG'] = round(season_data['BLK'] / season_data['GP'], 1)
        else:
            season_data['BLKPG'] = 0

        # rebounds per game
        if season_data['GP'] > 0 and season_data['REB'] is not None:
            season_data['RPG'] = round(season_data['REB'] / season_data['GP'], 1)
        else:
            season_data['RPG'] = 0

        # steals per game
        if season_data['GP'] > 0 and season_data['STL'] is not None:

templates/nba_stats/career_stats.html
{% extends 'base.html' %}
{% load humanize %}
{% load custom_tags %}
{% load static %}
{% block title %}
{{ player_full_name }} Stat Totals
{% endblock %}

{% block content %}
<div class="container mt-4">

    <!-- Player Card -->
    <div class="card mb-4">
        <div class="card-body">
            <div class="row">
                <!-- Player Image -->
                <div class="col-md-4 text-center">
                    <a href="{% url 'nba_stats:player_details' player_full_name=player_full_name player_id=player_id %}">
                        <img src="{{ player_headshot.0 }}" style="background-color: {{ player_headshot.1 }}" alt="Player Image" class="rounded-circle img-fluid mt-3  w-75">
                    </a>
                </div>

                <!-- Player Bio -->
                <div class="col-md-4 d-flex flex-column justify-content-center"  id="player-bio">
                    <h1 class="card-title" style="color: #b4513e;">{{ player_full_name }} #{{ player_bio.number }}</h1>
                    <h6><b>School:</b> {{ player_bio.education }} | <b>Country:</b> {{ player_bio.country }}</h6>
                    <h6><b>Height:</b> {{ player_bio.height }} | <b>Weight:</b> {{ player_bio.weight }}</h6>
                    <h6><b>Year:</b> {{ player_bio.year }}</h6>
                    <h6><b>Position:</b> {{ player_bio.position }} | <b>Status:</b> {{ player_bio.status }}</h6>
                    <h6><b>PPG:</b> {{ player_bio.PTS }} | <b>RPG:</b> {{ player_bio.REB }} | <b>APG:</b> {{ player_bio.AST }} <b>STLPG:</b> {{ player_bio.STL }} <b>BLKPG:</b> {{ player_bio.BLK }}</h6>
                 <!-- <button class="btn btn-outline-success mt-3"
                            hx-get="{% url 'nba_stats:update_player_bio' player_id=player_id player_name=player_full_name %}"
                            hx-target="#player-bio"
                            hx-swap="outerHTML"
                            hx-trigger="click">
                        Update Bio
                    </button> -->
                </div>

                <!-- Career Awards -->
                <div class="col-md-4 d-flex flex-column justify-content-center" id="player-awards">
                    <h4>Career Awards</h4>
                    <hr>
                    <button class="btn btn-outline-success mt-3"
                            hx-get="{% url 'nba_stats:update_player_awards' player_id=player_id player_name=player_full_name %}"
                            hx-target="#player-awards"
                            hx-swap="outerHTML"
                            hx-trigger="click">
                        Show Career Awards
                    </button>
                    <form id="download-form" method="get" 
                    action="{% url 'nba_stats:export_career_stats' player_full_name=player_full_name player_id=player_id %}">
                  <button type="submit" class="btn btn-success mt-2" onclick="handleDownload(event)">Export Career Stats</button>
              </form>
              <script>
                document.addEventListener("DOMContentLoaded", function () {
                    // Store the referring page in localStorage
                    if (document.referrer) {
                        localStorage.setItem("lastPage", document.referrer);
                    }
                });
                
                function handleDownload(event) {
                    event.preventDefault();  // Prevent default form submission
                
                    var form = document.getElementById("download-form");
                    var url = form.getAttribute("action");
                
                    // Create a hidden link to trigger download
                    var link = document.createElement("a");
                    link.href = url;
                    document.body.appendChild(link);
                    link.click();
                    document.body.removeChild(link);
                
                    // Retrieve last visited page from localStorage (fallback to home page)
                    var lastPage = localStorage.getItem("lastPage") || "/";
                
                    // Redirect back after 3 seconds
                    setTimeout(function() {
                        window.location.href = lastPage;
                    }, 3000);
                }
                </script>
                </div>
            </div>
        </div>
        <div class="card-footer d-flex justify-content-between">
            <div class="text-muted">{{ player_full_name }}</div>
            <div class="text-muted">#{{ player_bio.number }}</div>
        </div>
    </div>

    <!-- Player Details Table -->
    <div class="row">
        <div class="col-md-12">
            <h2 class="mt-4">Career Totals</h2>
            <div class="table-responsive">
                <table class="table table-bordered mt-2">
                    <thead>
                        <tr>
                            <th>Points</th>
                            <th>Assists</th>
                            <th>Blocks</th>
                            <th>Steals</th>
                            <th>Rebounds</th>
                            <th>Defensive Rebs</th>
                            <th>Offensive Rebs</th>
                            <th>3pt Attempts</th>
                            <th>3pt Makes</th>
                            <th>3pt %</th>
                            <th>FG Attempts</th>
                            <th>FG Makes</th>
                            <th>FG %</th>
                            <th>FT Attempts</th>
                            <th>FT Makes</th>
                            <th>FT %</th>
                            <th>Turnovers</th>
                            <th>Games Played</th>
                            <th>Games Started</th>
                            <th>Minutes</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for season_data in player_stats %}
                        <tr>
                            <td>{{ season_data.PTS|intcomma }}</td>
                            <td>{{ season_data.AST|intcomma }}</td>
                            <td>{{ season_data.BLK|intcomma }}</td>
                            <td>{{ season_data.STL|intcomma }}</td>
                            <td>{{ season_data.REB|intcomma }}</td>
                            <td>{{ season_data.DREB|intcomma }}</td>
                            <td>{{ season_data.OREB|intcomma }}</td>
                            <td>{{ season_data.FG3A|intcomma }}</td>
                            <td>{{ season_data.FG3M|intcomma }}</td>
                            <td>{{ season_data.FG3_PCT|percentage }}</td>
                            <td>{{ season_data.FGA|intcomma }}</td>
                            <td>{{ season_data.FGM|intcomma }}</td>
                            <td>{{ season_data.FG_PCT|percentage }}</td>
                            <td>{{ season_data.FTA|intcomma }}</td>
                            <td>{{ season_data.FTM|intcomma }}</td>
                            <td>{{ season_data.FT_PCT|percentage }}</td>
                            <td>{{ season_data.TOV|intcomma }}</td>
                            <td>{{ season_data.GP|intcomma }}</td>
                            <td>{{ season_data.GS|intcomma }}</td>
                            <td>{{ season_data.MIN|intcomma }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Forms for Viewing Table and Graphs -->
    <hr>
    <div class="container">
        <h3>Career Totals: Table</h3>
        <form method="post" class="form-inline">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary btn-lg" id="loadButton" type="submit">View Table</button>
        </form>
    </div>
    <hr>
    <div class="container">
        <h3>Career Trends: Graphs</h3>
        <form method="post" class="form-inline">
            {% csrf_token %}
            {{ graph_form.as_p }}
            <button class="btn btn-primary btn-lg" id="loadButton" type="submit">View Graph</button>
        </form>
    </div>
</div>
<hr>
{% endblock %}

templates/nba_stats/graph_comparison.html
{% extends 'base.html' %}
{% load humanize %}
{% load custom_tags %}
{% load static %}
{% block title %}
{{ player1_full_name }} & {{ player2_full_name }} Visual
{% endblock %}

{% block content %}
<h1 class="text-center">Player Comparison</h1>

<div class="container mt-4">
  <div class="row">
    <!-- Player 1 Card -->
    <div class="col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body text-center">
          <h2 class="card-title" style="color: #b4513e;">{{ player1_full_name }}</h2>
          <a href="{% url 'nba_stats:player_details' player_full_name=player1_full_name player_id=player1_id %}">
            <img src="{{ player1_headshot.0 }}" alt="{{ player1_full_name }} Headshot" class="rounded-circle img-fluid mt-3 w-75" style="background-color:{{ player1_headshot.1 }};">
          </a>
          <h6><b>PPG:</b> {{ player1_bio.PTS }} | <b>RPG:</b> {{ player1_bio.REB }} | <b>APG:</b> {{ player1_bio.AST }}</h6>
        </div>
        <!-- Career Awards for Player 1 -->
        <div class="card-footer text-center" id="player1-awards">
          <button class="btn btn-outline-success"
                  hx-get="{% url 'show_career_awards_player1' player1_name=player1_full_name player1_id=player1_id %}"
                  hx-target="#player1-awards"
                  hx-swap="outerHTML"
                  hx-trigger="click">
            Show Career Awards
          </button>
        </div>
      </div>
    </div>

    <!-- Player 2 Card -->
    <div class="col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body text-center">
          <h2 class="card-title" style="color: #b4513e;">{{ player2_full_name }}</h2>
          <a href="{% url 'nba_stats:player_details' player_full_name=player2_full_name player_id=player2_id %}">
            <img src="{{ player2_headshot.0 }}" alt="{{ player2_full_name }} Headshot" class="rounded-circle img-fluid mt-3 w-75" style="background-color:{{ player2_headshot.1 }};">
          </a>
          <h6><b>PPG:</b> {{ player2_bio.PTS }} | <b>RPG:</b> {{ player2_bio.REB }} | <b>APG:</b> {{ player2_bio.AST }}</h6>
        </div>
        <!-- Career Awards for Player 2 -->
        <div class="card-footer text-center" id="player2-awards">
          <button class="btn btn-outline-success"
                  hx-get="{% url 'show_career_awards_player2' player2_name=player2_full_name player2_id=player2_id %}"
                  hx-target="#player2-awards"
                  hx-swap="outerHTML"
                  hx-trigger="click">
            Show Career Awards
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- Graph Section -->
  <div class="text-center mt-4">
    <img src="data:image/png;base64,{{ graph }}" alt="Graph" class="img-fluid" style="max-width: 100%; height: auto;">
  </div>

  <!-- Back to Comparison Button -->
  <div class="text-center mt-4">
    <a href="{% url 'nba_stats:compare_profiles' player1_full_name=player1_full_name player1_id=player1_id player2_full_name=player2_full_name player2_id=player2_id %}" class="btn btn-primary">
      Back To {{ player1_full_name }} / {{ player2_full_name }} Comparison Page
    </a>
  </div>
</div>

{% endblock %}

templates/nba_stats/player_graph.html
{% extends 'base.html' %}
{% load humanize %}
{% load custom_tags %}
{% load static %}
{% block title %}
{{ player_full_name }} {{ category }} Graph
{% endblock %}

{% block content %}
 <div class="container mt-4">
   <!-- Player Card -->
    <div class="card mb-4">
        <div class="card-body">
            <div class="row">
                <!-- Player Image -->
                <div class="col-md-4 text-center">
                    <a href="{% url 'nba_stats:player_details' player_full_name=player_full_name player_id=player_id %}">
                        <img src="{{ player_headshot.0 }}" style="background-color: {{ player_headshot.1 }}" alt="Player Image" class="rounded-circle img-fluid mt-3  w-75">
                    </a>
                </div>

                <!-- Player Bio -->
                <div class="col-md-4 d-flex flex-column justify-content-center">
                    <h1 class="card-title" style="color: #b4513e;">{{ player_full_name }}</h1>
                    <h6><b>School:</b> {{ player_bio.education }} | <b>Country:</b> {{ player_bio.country }}</h6>
                    <h6><b>Height:</b> {{ player_bio.height }} | <b>Weight:</b> {{ player_bio.weight }}</h6>
                    <h6><b>Year:</b> {{ player_bio.year }} | <b>Number:</b> {{ player_bio.number }}</h6>
                    <h6><b>Position:</b> {{ player_bio.position }} | <b>Status:</b> {{ player_bio.status }}</h6>
                    <h6><b>PPG:</b> {{ player_bio.PTS }} | <b>RPG:</b> {{ player_bio.REB }} | <b>APG:</b> {{ player_bio.AST }} <b>STLPG:</b> {{ player_bio.STL }} <b>BLKPG:</b> {{ player_bio.BLK }}</h6>
                </div>

                <!-- Career Awards -->
                <div class="col-md-4 d-flex flex-column justify-content-center" id="player-awards">
                    <h4>Career Awards</h4>
                    <hr>
                    <button class="btn btn-outline-success mt-3"
                            hx-get="{% url 'nba_stats:update_player_awards' player_id=player_id player_name=player_full_name %}"
                            hx-target="#player-awards"
                            hx-swap="outerHTML"
                            hx-trigger="click">
                        Show Career Awards
                    </button>
                </div>
            </div>
        </div>
        <div class="card-footer d-flex justify-content-between">
            <div class="text-muted">{{ player_full_name }}</div>
            <div class="text-muted">#{{ player_bio.number }}</div>
        </div>
    </div>
     <div class="text-center">
    <img src="data:image/png;base64,{{ graph }}" alt="graph" style="max-width: 100%; height: auto;">
</div>
       <a href="{% url 'nba_stats:player_details' player_full_name=player_full_name player_id=player_id %}" class="btn btn-primary">Back To {{ player_full_name }} Page</a>
        </div>

{% endblock %}